name: Pytorch_Retinaface
channels:
  - pytorch
  - conda-forge
  - pytorch3d
dependencies:
  - python=3.8
  - pip
  - pytorch3d
  - pip:
      - torch>=1.8.0
      - torchvision
      - opencv-python
      - pillow
      - scikit-image
      - scipy
      - tensorboard
      - tqdm