name: Pytorch_Retinaface
channels:
  - pytorch
  - conda-forge
  - pytorch3d
dependencies:
  - python=3.9
  - pip
  - pytorch3d
  - pip:
      - torch
      - torchvision
      - opencv-python
      - pillow
      - scikit-image
      - scipy
      - tensorboard
      - tqdm